=== kennycason/kennycason/code/java/nndev/traindata/data.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Author: Kenny Cason -->
<!-- Email: kenneth.cason AT gmail DOT com -->
<!-- Website: www.kennycason.com -->
<!-- Date: 2008 Nov 1 -->

<!-- Training Data Specifications -->
<!ELEMENT traindata (pre*,innodes,midlayers,midnodes,outnodes,learnrate,maxcycles,error,data*)>
  <!-- prerequisite knowledge to learn -->
  <!ELEMENT pre (#PCDATA)>
  <!-- number of input nodes -->
  <!ELEMENT innodes (#PCDATA)>
  <!-- number of middle layers -->
  <!ELEMENT midlayers (#PCDATA)>
  <!-- number of nodes in the middle layer -->
  <!ELEMENT midnodes (#PCDATA)>
  <!-- number of output nodes -->
  <!ELEMENT outnodes (#PCDATA)>
  <!-- learning rate -->
  <!ELEMENT learnrate (#PCDATA)>
  <!-- max number of iterations to teach for -->
  <!ELEMENT maxcycles (#PCDATA)>
  <!-- error to train until -->
  <!ELEMENT error (#PCDATA)>
  <!-- number of data --> 
  <!ELEMENT numdata (#PCDATA)>
  <!-- dimensional information about how to view the input and output -->
  <!ELEMENT inwidth (#PCDATA)>
  <!ELEMENT inheight (#PCDATA)>
  <!ELEMENT outwidth (#PCDATA)>
  <!ELEMENT outheight (#PCDATA)>
  <!-- information about the data to be teached -->
  <!ELEMENT data (in*,out*)>
    <!-- input -->
    <!ELEMENT in (#PCDATA)>
    <!-- desired output -->
    <!ELEMENT out (#PCDATA)>

=== kennycason/kennycason/code/java/nndev/traindata/logicalORSimple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wccs SYSTEM "data.dtd">

<!-- Author: Kenny Cason -->
<!-- Email: kenneth.cason AT gmail DOT com -->
<!-- Website: www.kennycason.com -->
<!-- Date: 2008 Nov 1 -->

<!-- Logical OR -->
<traindata>
  <innodes>2</innodes>
  <midlayers>1</midlayers>
  <midnodes>2</midnodes>
  <outnodes>1</outnodes>
  <learnrate>10.5</learnrate>
  <maxcycles>100000</maxcycles>
  <error>.0001</error>
  <numdata>4</numdata>
  <data>
    <in>0</in>
    <in>0</in>
    <out>0</out>
  </data>
  <data>
    <in>0</in>
    <in>1</in>
    <out>1</out>
  </data>
  <data>
    <in>1</in>
    <in>0</in>
    <out>1</out>
  </data>
  <data>
    <in>1</in>
    <in>1</in>
    <out>1</out>
  </data>
</traindata>
